### ISSUE TITLE
Parent Collection - Challenges

### ISSUE THREAD

**Issue by goodnekk** [CodeForEindhoven/IdeaGarden#25]
Currently all messages and pages are hard coded. There should be some kind of cms type system for this.

**Comment by milovanderlinden** [comment]
That is what I also mean by i18n. We need internationalization form common
messages and should store the Challenge specific texts inside mongodb.

2016-06-30 17:13 GMT+02:00 Marcel Goethals <notifications@github.com>:

> Currently all messages and pages are hard coded. There should be some kind
> of cms type system for this.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CodeForEindhoven/IdeaGarden/issues/25>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAGeNthKkP9hNzXqL79ar-e1JynOwB0-ks5qQ90RgaJpZM4JCRFZ>
> .
>



-- 
[image: http://www.dogodigi.net] <http://www.dogodigi.net>
*Milo van der Linden*
web: dogodigi <http://www.dogodigi.net>
tel: +31-6-16598808

**Comment by milovanderlinden** [comment]
This would best be a parent collection for ideas in the mongo database. I suggest that we call this a challenge (the challenges collection), where as all ideas plus the underlying objects belong to a challenge.

Challenges can have (in the sequence that is currently on the __question__ page)

# Main
- Intro text:

> Eindhoven nodigt je uit om jouw stad mooier, leuker, chiller en aantrekkelijker te maken!
>
> Heel de maand juli kun je reageren op de vraag:

- Leader image
- title:

> Hoe zou jij Strijp-S met het Centrum verbinden?

- video
- How?
- Why?
  - Explaining text (see current homepage)
- When?
  - timeframe for this challenge

# Various

- Contact
  - Name
  - E-mail
- Rules (rules page)
- Game/Prize system (explain page)
- Disclaimer
- Sponsor and organization logo's to display in the footer

**Comment by goodnekk** [comment]
This is a good outline. I think we should try to be nonrestrictive. In other words, try to avoid limiting input to just these elements where possible, allow for basic extension/rearranging.

**Comment by milovanderlinden** [comment]
Challenge Collection plus sample script created.
