### ISSUE TITLE
Fish sizing and sequence algorithm

### ISSUE THREAD

**Issue by milovanderlinden** [CodeForEindhoven/IdeaGarden#31]
It is unclear to me why a small fish with one kudo is shown before a big fish with one kudo (see screenshot) we should check the algorithm and maybe also explain the algorithm in more details to users.

![fish-issue](https://cloud.githubusercontent.com/assets/106038/16517748/643c66e8-3f7f-11e6-9a7f-b666781f57ea.png)

**Comment by basbiezemans** [comment]
It looks like the cards are sorted by vote count:

`sort(function(a,b){
    return b.votecount - a.votecount;
});` (Models.js).

This explains the order in which they appear at the moment. However, badge stage is determined by `idea.additions.length` (IdeaDetailPage.js and Badge.js).

How about this? The cards are sorted by vote count. Cards with the same vote count are sorted by badge stage.

`var delta = b.votecount - a.votecount;`
`if (delta == 0) { delta = b.additions.length - a.additions.length; }`
`return delta;`

**Comment by goodnekk** [comment]
Thanks Bas! Great suggestion!
