### ISSUE TITLE
Voting in i.e. does not work

### ISSUE THREAD

**Issue by goodnekk** [CodeForEindhoven/IdeaGarden#39]
I.E. 11 > no voting

**Comment by basbiezemans** [comment]
It works in IE 11 but you have to refresh the page to see the result.

**Comment by basbiezemans** [comment]
Just a hunch but try removing the first (empty) line in the index.html file.

**Comment by goodnekk** [comment]
I think I found (at least part) of the problem: IE rather aggressively caches ajax requests. This of course prevents votes from ever reaching the server...
