### ISSUE TITLE
line break characters in description don't show up

### ISSUE THREAD

**Issue by goodnekk** [CodeForEindhoven/IdeaGarden#47]

**Comment by basbiezemans** [comment]
Newline to break function? For example:

```javascript
function nl2br(str) {
    return String(str).replace('/\r\n|\n\r|\r|\n/g', '<br>');
}
```

**Comment by goodnekk** [comment]
If only life was so easy. :) I'd like to avoid directly injecting html and rather embed it into mitril's dom-tree.
I embedded the regex into the already existing linkify function.
